name: Python CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # Install system dependencies required for PySide6 on headless Linux
        sudo apt-get update
        sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xinerama0 libxcb-xfixes0 libxcb-xinput0 xvfb

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Test application launch
      run: |
        # Run the application in a virtual framebuffer to see if it launches
        xvfb-run python widget.py &
        PID=$!
        sleep 10 # Give the application time to initialize
        # Check if the process is still running
        if ps -p $PID > /dev/null; then
          echo "Application launched successfully."
          kill $PID
        else
          echo "Application failed to launch."
          exit 1
        fi
